Nick/aug5reviews
tlswg/tls-exported-authenticator pull request #74
Opened 2021-08-06 00:07 UTC by grittygrease

2021-08-20 13:29 UTC, chris-wood approved these changes

2021-08-20 13:29 UTC, chris-wood commented on draft-ietf-tls-exported-authenticator.md
> +using a Certificate message after the session
This might change based on @kaduk's review (CertificateVerify instead of Certificate).

2021-08-20 13:29 UTC, chris-wood commented on draft-ietf-tls-exported-authenticator.md
> +datastructure in the software to simplify the implementation.
```suggestion
datastructure in the software to simplify implementation.
```

2021-08-20 13:29 UTC, chris-wood commented on draft-ietf-tls-exported-authenticator.md
> +ClientCertificateRequest created as part of client-generated certificate requests.
```suggestion
ClientCertificateRequest created as part of client-generated authenticator requests.
```

2021-08-20 13:29 UTC, chris-wood commented on draft-ietf-tls-exported-authenticator.md
> +ClientCertificateRequest created as part of client-generated certificate requests.
(To try and make it more clear that this only pertains to this draft, and not the main TLS handshake.)

2021-08-20 13:29 UTC, chris-wood commented
@grittygrease I think #73 should land first, and then we should rebase this on top of those changes. Feel free to ignore #75, too, if we think the best outcome here is to simply clarify inline.

2021-10-22 01:12 UTC, seanturner requested changes
Please not the change on line 493.

2021-10-22 01:12 UTC, seanturner commented on draft-ietf-tls-exported-authenticator.md
> +The addition of "CR" to this column does not authorize the use of this extension
@grittygrease I think we split the difference between adding a column and just having the text in the I-D but making sure the text is in the registry by asking IANA to add a note with text like:

      IANA is also requested to add the following note to the registry:
 
      The addition of the "CR" to the "TLS 1.3" column for the server_name(0) extension does not ...

2021-10-22 01:41 UTC, seanturner commented
@grittygrease unless you hear otherwise merge this after 29 October 2021

2021-10-22 14:04 UTC, richsalz commented on draft-ietf-tls-exported-authenticator.md
> +The addition of "CR" to this column does not authorize the use of this extension
I think this is shorter and more clear, ignore if you disagree:
The addition of the "CR" to the "TLS 1.3" column for the server_name(0) extension only marks the extension as valid in a ClientCertificateRequest created as part of client-generated authenticator requests.

2021-10-22 14:13 UTC, seanturner commented on draft-ietf-tls-exported-authenticator.md
> +The addition of "CR" to this column does not authorize the use of this extension
lgtm

2021-10-25 19:27 UTC, grittygrease commented on draft-ietf-tls-exported-authenticator.md
> +The addition of "CR" to this column does not authorize the use of this extension
Text updated. Let me know if this matches what you expect.

2021-10-27 13:15 UTC, seanturner approved these changes

2021-10-27 13:15 UTC, seanturner commented on draft-ietf-tls-exported-authenticator.md
> +The addition of "CR" to this column does not authorize the use of this extension
lgtm

2021-10-29 18:09 UTC, merged

2021-10-29 18:09 UTC, chris-wood approved these changes